site_name: Clip Bond Docs
site_description: Describe what your site is about  # 设置文档网站的描述
site_url: 'https://example.com'  # 设置文档网站的 URL

theme:
  name: material
  language: en  # zh en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal

  features:
    #- navigation.instant
    #- navigation.sections         #启用了导航栏的章节功能。
    #- toc.integrate               #允许用户快速浏览文档的结构和内容。
    - navigation.top              #启用了返回页面顶部的功能
    - search.suggest              #启用了搜索建议功能
    - search.highlight            #启用了搜索结果高亮功能。
    - content.tabs.link           #启用了内容区域的选项卡链接功能
    - content.code.annotation     #启用了对代码块进行注释的功能
    - content.code.copy           #启用了复制代码块的功能。
    - navigation.tabs             #启用了导航栏的选项卡功能。

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - offline

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
  - stylesheets/stylish.css


nav:  # 定义导航栏
  - Tutorials: 
    - Home: index.md  # 首页链接
    - 1.Software Init:
      - 1.1.Edit EPJ File: home/1.1.Edit_EPJ_File.md
      - 1.2.Operator Interface: home/1.2.Operator_Interface.md
      - 1.3.Equipment States: home/1.3.Equipment_Processing_States.md
    - 2.Alarms:
      - 2.Alarms: home/2.Alarms.md
    - 3.Variables:
      - 3.1.Status Variables: home/3.1.Status_Variables.md
      - 3.2.Data Variables: home/3.2.Data_Variables.md
      - 3.3.Equipment Constants: home/3.3.Equipment_Constants.md
    - 4.Events:
      - 4.1.Collection Events: home/4.1.Collection_Events.md
    - 5.Data Transfer:
      - 5.1.Remote Commands: home/5.1.Remote_Commands.md
      - 5.2.Custom Messaging: home/5.2.Custom_Messaging.md
      - 5.3.Recipe Management: home/5.3.Recipe_Management.md
    - 6.E142 (No training):
      - 6.1.Wafer Mapping: home/6.1.Wafer_Mapping.md
      - 6.2.Strip Mapping: home/6.2.Strip_Mapping.md
    - 7.Delivery Requirements:
      - 7.1.Communications Manual: home/7.1.Communications_Manual.md
      - 7.2.Trace Data Collection: home/7.2.Trace_Data_Collection.md
      - 7.3.Communication command test: home/7.3.Communication_command_test.md
    - 8.Software Tutorials:
      - 8.1.CIMConnect: home/8.1.CIMConnect.md
      - 8.2.EquipmentTest: home/8.2.EquipmentTest.md
      - 8.3.Remote Connection: home/8.3.Remote_Connection.md
      - 8.4.Client_Needs: home/8.4.Client_Needs.md
  - SECS/GEM_Alarms:
    - 01-Avaline_C: SG_Alarms/01-Avaline_C.md  #
    - 02-CCD: SG_Alarms/02-CCD.md  # 相机
    - 03-ClipBondCode: SG_Alarms/03-ClipBondCode.md  #
    - 04-ClipBondUl: SG_Alarms/04-ClipBondUl.md  #
    - 05-ClipFeederCode: SG_Alarms/05-ClipFeederCode.md  #
    - 06-ClipFeederUI: SG_Alarms/06-ClipFeederUI.md  #
    - 07-CarryABC: SG_Alarms/07-CarryABC.md  #
    - 08-CarryUI: SG_Alarms/08-CarryUI.md  #
    - 09-LoginUl: SG_Alarms/09-LoginUl.md  #
    - 10-Map: SG_Alarms/10-Map.md  #
    - 11-MaterialsDataDll: SG_Alarms/11-MaterialsDataDll.md  #
    - 12-Temperature: SG_Alarms/12-Temperature.md  #
    - 13-TinA: SG_Alarms/13-TinA.md  #
    - 14-TinAUI: SG_Alarms/14-TinAUI.md  #
    - 15-TinB: SG_Alarms/15-TinB.md  #
    - 16-TinBUI: SG_Alarms/16-TinBUI.md  #
    - 17-UITool: SG_Alarms/17-UITool.md  #
    - All alarm: SG_Alarms/All alarm.md
    - README: SG_Alarms/README.md  #
  - SECS/GEM_Variables:
    - 01-Status Variables: SG_Variables/01-Status_Variables.md  #
    - 02-Data Variables: SG_Variables/02-Data_Variables.md  # 相机
    - 03-Equipment Constants: SG_Variables/03-Equipment_Constants.md  #
    - README: SG_Variables/README.md  #
  - SECS/GEM_Events:
    - README: SG_Events/README.md  #
  - ASMPT: 
    - 1.Software Init:
      - 1.1.States Models: ASMPT/1.1.States_Models.md
      - 1.2.Equipment Capabilities: ASMPT/1.2.Equipment_Capabilities.md
      - 1.2.Operator Interface: ASMPT/1.2.Operator_Interface.md
      - 1.3.Equipment States: ASMPT/1.3.Equipment_Processing_States.md
    - 2.Alarms:
      - 2.Alarms: ASMPT/2.Alarms.md
    - 3.Variables:
      - 3.1.Status Variables: ASMPT/3.1.Status_Variables.md
      - 3.2.Data Variables: ASMPT/3.2.Data_Variables.md
      - 3.3.Equipment Constants: ASMPT/3.3.Equipment_Constants.md
    - 4.Events:
      - 4.1.Collection Events: ASMPT/4.1.Collection_Events.md
    - 5.Data Transfer:
      - 5.1.Remote Commands: ASMPT/5.1.Remote_Commands.md
      - 5.2.Custom Messaging: ASMPT/5.2.Custom_Messaging.md
      - 5.3.Recipe Management: ASMPT/5.3.Recipe_Management.md
  - SECS/E142:
    - CimetrixInstall: E142/CimetrixInstall.md
    - StripMap: E142/StripMap.md  #
    - WaferMap: E142/WaferMap.md  #
    - StripAndWafer: E142/StripAndWafer.md  #